# ----------------------------------
# Pterodactyl Plutonium Egg Dockerfile
# Environment: Ubuntu 20.04
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM ghcr.io/hyperbeats/docker-image/ptero-wine:latest

LABEL maintainer="HyperBeats" maintainer="contact-hyperbeats@protonmail.com"

USER root

COPY checkupdater.sh /checkupdater.sh
#Make sure the script is executable by anyone
RUN chmod ugo+x /checkupdater.sh

USER container
ENV  USER=container HOME=/home/container

WORKDIR /home/container/

COPY entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]